on:
  pull_request:
    types: [synchronize, opened, reopened, closed]
env:
  CI: true
  TZ: Asia/Tokyo
  HUSKY_SKIP_INSTALL: 1
  PR_NUMBER: ${{ github.event.number }}
  ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cache-version: cache-0.0.0
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "now:  v`now --version`"
      - run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  check:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ env.cache-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ env.cache-version }}-yarn-
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run lint:js
      - run: yarn run lint:css
      - run: yarn run typecheck
  build:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
    needs: check
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ env.cache-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ env.cache-version }}-yarn-
      - uses: actions/cache@v1
        id: build-cache
        with:
          path: .next
          key: ${{ env.cache-version }}-build-${GITHUB_SHA}
          restore-keys: ${{ env.cache-version }}-build-${GITHUB_SHA}
      - run: yarn run build
        if: steps.build-cache.outputs.cache-hit != 'true'
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ env.cache-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ env.cache-version }}-yarn-
      - uses: actions/cache@v1
        id: build-cache
        with:
          path: .next
          key: ${{ env.cache-version }}-build-${GITHUB_SHA}
          restore-keys: ${{ env.cache-version }}-build-${GITHUB_SHA}
      - run: >
          now
          --no-clipboard
          --token ${ZEIT_TOKEN}
          > ${HOME}/deployment.txt
      - run: >
          now
          alias
          --token ${ZEIT_TOKEN}
          `cat ${HOME}/deployment.txt`
          ymkzco-pr-${PR_NUMBER}.now.sh
      - run: cat ${HOME}/deployment.txt
      - run: >
          curl
          -X POST
          -H "Authorization: token $GITHUB_TOKEN"
          -d "{ \"body\": \"ðŸŒ Preview: https://ymkzco-pr-${PR_NUMBER}.now.sh\" }"
          ${{ github.event.pull_request.comments_url }}
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
  cleanup-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - run: >
          now
          remove
          --yes
          --token ${ZEIT_TOKEN}
          `cat ${HOME}/deployment.txt`
