on:
  push:
    branches:
      - master
env:
  CI: true
  TZ: Asia/Tokyo
  CACHE: alpha
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "now:  v`now --version`"
      - run: |
          echo "CI: ${CI}"
          echo "TZ: ${TZ}"
          echo "CACHE: ${CACHE}"
      - run: date
      - run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=version::$(cat .node-version)"
        id: node-version
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ env.CACHE }}-${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ env.CACHE }}-${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run lint:js
      - run: yarn run lint:css
      - run: yarn run typecheck
